### ISSUE TITLE
# Some error occurs.

### ISSUE THREAD

**Issue by Trikim-Zhang** [calculix/inp2unv#1]
# Some error occurs.
``` python
Traceback (most recent call last):
  File "C:\Users\Hang\Desktop\test\inp2unv-main\inp2unv\inp2unv.py", line 63, in <module>
    inp2unv.run()
  File "C:\Users\Hang\Desktop\test\inp2unv-main\inp2unv\inp2unv.py", line 45, in run
    writer.write(fem, self.unv_file_name)
  File "C:\Users\Hang\Desktop\test\inp2unv-main\inp2unv\writer.py", line 64, in write
    f.write(line1.format(e.num, unv_element_type, 2, 1, 7, len(e.nodes)))
TypeError: unsupported format string passed to NoneType.__format__

**Comment by imirzov** [comment]
Hi!
Please, could you also attach the file you're trying to convert?
